---
name: Build and Push Docker Image for serverless

on:
  push:
    branches:
      - main
    paths:
      - 'serverless/**'
  workflow_dispatch:

jobs:
  docker-build-serverless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd serverless

          IMAGE_VERSION=$(grep -oP '^ARG IMAGE_VERSION=\K.*' Dockerfile)
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${IMAGE_VERSION}"

          SERVERLESS_VERSION=$(grep -oP "^ARG SERVERLESS_VERSION=\K.*" Dockerfile)
          echo "SERVERLESS_VERSION=${SERVERLESS_VERSION}" >> $GITHUB_ENV
          echo "SERVERLESS_VERSION=${SERVERLESS_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: serverless
          file: serverless/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/serverless:${{ env.SERVERLESS_VERSION }}-alpine${{ env.IMAGE_VERSION }}
            opslabhq/serverless:${{ env.SERVERLESS_VERSION }}
            opslabhq/serverless:alpine${{ env.IMAGE_VERSION }}
            opslabhq/serverless:latest
