---
name: Build and Push Docker Image for kubectl

on:
  push:
    branches:
      - main
    paths:
      - 'kubectl/**'
  workflow_dispatch:

jobs:
  docker-build-kubectl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd kubectl

          IMAGE_VERSION=$(grep -oP '^ARG IMAGE_VERSION=\K.*' Dockerfile)
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${IMAGE_VERSION}"

          KUBECTL_VERSION=$(grep -oP "^ARG KUBECTL_VERSION=\K.*" Dockerfile)
          echo "KUBECTL_VERSION=${KUBECTL_VERSION}" >> $GITHUB_ENV
          echo "KUBECTL_VERSION=${KUBECTL_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: kubectl
          file: kubectl/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/kubectl:${{ env.KUBECTL_VERSION }}-alpine${{ env.IMAGE_VERSION }}
            opslabhq/kubectl:${{ env.KUBECTL_VERSION }}
            opslabhq/kubectl:alpine${{ env.IMAGE_VERSION }}
            opslabhq/kubectl:latest
