---
name: Build Docker Image Renovate PR for python

on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker-build-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (Dry run)
        uses: docker/build-push-action@v6
        with:
          context: python
          file: python/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: |
            opslabhq/python:test_pr
