---
name: Build and Push Docker Image for ansible

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

jobs:
  docker-build-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd ansible

          IMAGE_VERSION=$(grep -oP '^ARG IMAGE_VERSION=\K.*' Dockerfile)
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${IMAGE_VERSION}"

          ANSIBLE_VERSION=$(grep -oP "^ARG ANSIBLE_VERSION=\K.*" Dockerfile)
          echo "ANSIBLE_VERSION=${ANSIBLE_VERSION}" >> $GITHUB_ENV
          echo "ANSIBLE_VERSION=${ANSIBLE_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ansible
          file: ansible/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/ansible:${{ env.ANSIBLE_VERSION }}-alpine${{ env.IMAGE_VERSION }}
            opslabhq/ansible:${{ env.ANSIBLE_VERSION }}
            opslabhq/ansible:alpine${{ env.IMAGE_VERSION }}
            opslabhq/ansible:latest
