---
name: Build and Push Docker Image for terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  docker-build-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd terraform

          IMAGE_VERSION=$(grep -oP '^ARG IMAGE_VERSION=\K.*' Dockerfile)
          echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=${IMAGE_VERSION}"

          TERRAFORM_VERSION=$(grep -oP "^ARG TERRAFORM_VERSION=\K.*" Dockerfile)
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}" >> $GITHUB_ENV
          echo "TERRAFORM_VERSION=${TERRAFORM_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: terraform
          file: terraform/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/terraform:${{ env.TERRAFORM_VERSION }}-alpine${{ env.IMAGE_VERSION }}
            opslabhq/terraform:${{ env.TERRAFORM_VERSION }}
            opslabhq/terraform:alpine${{ env.IMAGE_VERSION }}
            opslabhq/terraform:latest
