---
name: Build and Push Docker Image for docker

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  docker-build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd docker

          DOCKER_VERSION=$(grep -oP "^ARG DOCKER_VERSION=\K.*" Dockerfile)
          echo "DOCKER_VERSION=${DOCKER_VERSION}" >> $GITHUB_ENV
          echo "DOCKER_VERSION=${DOCKER_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/docker:${{ env.DOCKER_VERSION }}-dind
            opslabhq/docker:latest
