---
name: Build Docker Image Renovate PR for miniconda

on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - 'miniconda/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker-build-miniconda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (Dry run)
        uses: docker/build-push-action@v6
        with:
<<<<<<< HEAD:.github/workflows/docker_buildx_miniconda-alpine_pr.yml
          context: miniconda-alpine
          file: miniconda-alpine/Dockerfile
          platforms: linux/amd64
=======
          context: miniconda
          file: miniconda/Dockerfile
          platforms: linux/amd64,linux/arm64
>>>>>>> 4a9a6ea (Update files):.github/workflows/docker_buildx_miniconda_pr.yml
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: |
            opslabhq/miniconda:test_pr
